djangoapp/app/urls.py
from django.urls import path
from app.views import index
from . import views

app_name = 'app'

urlpatterns = [
    path('', index, name='index'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
]

djangoapp/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

djangoapp/app/models.py
from django.db import models

# Create your models here.

djangoapp/app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class SignUpForm(UserCreationForm):
	email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email'}))
	first_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}))
	last_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}))


	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


	def __init__(self, *args, **kwargs):
		super(SignUpForm, self).__init__(*args, **kwargs)

		self.fields['username'].widget.attrs['class'] = 'form-control'
		self.fields['username'].widget.attrs['placeholder'] = 'User Name'
		self.fields['username'].label = ''
		self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

		self.fields['password1'].widget.attrs['class'] = 'form-control'
		self.fields['password1'].widget.attrs['placeholder'] = 'Password'
		self.fields['password1'].label = ''
		self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

		self.fields['password2'].widget.attrs['class'] = 'form-control'
		self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
		self.fields['password2'].label = ''
		self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'	

djangoapp/app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import SignUpForm


# Create your views here.
def index(request):
    message_negative = "Acesso Negado!"
    #Checked Login
    if request.method == "POST": 
        usuario = request.POST['usuario']
        senha = request.POST['senha']
        #Authenticate
        user = authenticate(request, username=usuario, password=senha)
        if user is not None:
            login(request,user)
            messages.success(request, "Acesso concedido com sucesso!")
            return redirect('app:index')
        else:
            messages.warning(request, message_negative)
            return redirect('app:index')
    else:
        return render(request, 'index.html')

def logout_user(request):
    logout(request)
    messages.success(request, "Sessão Encerrada com Sucesso!")
    return redirect('app:index')

def register_user(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			# Authenticate and login
			username = form.cleaned_data['username']
			password = form.cleaned_data['password1']
			user = authenticate(username=username, password=password)
			login(request, user)
			messages.success(request, "Seu registro foi realizado com sucesso!")
			return redirect('app:index')
	else:
		form = SignUpForm()
		return render(request, 'base/register.html', {'form':form})

	return render(request, 'base/register.html', {'form':form})

djangoapp/app/templates/base/base.html
<!doctype html>
<html lang="pt-br">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %}</title>
  {% load static %}
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>

<body>
  <header>
    {% include './navbar.html' %}
  </header>
  <main class="container">
    {% if messages %}
      {% for message in messages %}
      <div {% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" {% endif %}>
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
    {% endif %}
    {% block content %}{% endblock %}
  </main>
  <footer class="container">
    <p>&copy; 2024 APP</p>
  </footer>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

djangoapp/app/templates/base/login.html
<div class="col-md-6 offset-md-3">
    <h1>Login</h1>
    <form method="POST" action="{% url 'app:index' %}">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" class="form-control" id="username" name="username" required>
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" class="form-control" id="password" name="password" required>
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
</div>

djangoapp/app/templates/base/navbar.html
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">APP</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
          <li class="nav-item d-flex">
            <a class="nav-link" href="{% url 'app:logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item d-flex">
            <a class="nav-link" href="{% url 'app:register' %}">Register</a>
          </li>
          <li class="nav-item d-flex">
            <a class="nav-link" href="{% url 'app:index' %}">Login</a>
          </li>
          {% endif %}
      </div>
    </div>
  </nav>

djangoapp/app/templates/base/register.html
{% extends './base.html' %}
{% block content %}

{% if user.is_authenticated %}

<h1>You are already registered!</h1>

<a href="{% url 'app:index' %}" class="btn btn-secondary">Back to home</a>


{% else %}

<div class="col-md-6 offset-md-3">
    <h1>Register</h1>

    <form method="POST" action="">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            Seu formulário contém erros
            {% for field in form %}
            {% if field.errors %}
            {{ field.errors }}
            {% endif %}
            {% endfor %}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}

        {{ form.as_p }}

        <br />
        <button type="submit" class="btn btn-secondary">Register</button>
    </form>
</div>
{% endif %}
{% endblock %}

djangoapp/app/templates/index.html
{% extends './base/base.html' %}

{% block title %}Página Inicial{% endblock %}

{% block content %}

{% if user.is_authenticated %}
<h1>Home</h1>

<p>Enter homepage content!</p>

{% else %}

{% include './base/login.html' %}

{% endif %}

{% endblock %}